<?php
/**
 * Created by PhpStorm.
 * User: sven
 * Date: 07.04.2017
 * Time: 17:30
 */

namespace Grisu\Core;


class Ventil extends Sensor
{
    /**
     * Ventil constructor.
     * @param $dbconnection
     */
    public function __construct($dbconnection)
    {
        parent::__construct($dbconnection);
    }

    /**
     * @param $id
     * @return Sensor
     */
    public function getOne($id)
    {
        return parent::getOne($id); // TODO: Change the autogenerated stub
    }

    /**
     * @param $id
     */
    public function getAll($id)
    {
        parent::getAll($id); // TODO: Change the autogenerated stub
    }

    /**
     * @param $id
     */
    public function getByQuery($id)
    {
        parent::getByQuery($id); // TODO: Change the autogenerated stub
    }

    /**
     *
     */
    public function set()
    {
        parent::set(); // TODO: Change the autogenerated stub
    }

    /**
     * @param array $values
     * @param $query
     */
    public function updateByQuery(array $values, $query)
    {
        parent::updateByQuery($values, $query); // TODO: Change the autogenerated stub
    }

}